version: "2"

linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - dogsled
    - errcheck
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - goheader
    - mnd
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nestif
    - noctx
    - nolintlint
    - prealloc
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - unconvert
    - unused
    - whitespace
    - wsl_v5

  settings:
    mnd:
      checks:
        - condition
        - operation
        - return
    revive:
      rules:
        - name: comment-spacings
          arguments:
            - nolint
          severity: warning
          disabled: false
        - name: constant-logical-expr
          severity: warning
          disabled: false
        - name: datarace
          severity: warning
          disabled: false
        - name: defer
          severity: warning
          disabled: false
        - name: duplicated-imports
          severity: warning
          disabled: false
        - name: early-return
          severity: warning
          disabled: false
        - name: error-naming
          severity: warning
          disabled: false
        - name: error-strings
          severity: warning
          disabled: false
        - name: exported
          severity: warning
          disabled: false
        - name: optimize-operands-order
          severity: warning
          disabled: false
        - name: package-comments
          disabled: true
        - name: range-val-in-closure
          severity: warning
          disabled: false
        - name: range-val-address
          severity: warning
          disabled: false
        - name: superfluous-else
          severity: warning
          disabled: false
        - name: time-equal
          severity: warning
          disabled: false
        - name: unused-parameter
          severity: warning
          disabled: false
        - name: use-any
          severity: warning
          disabled: false
        - name: waitgroup-by-value
          severity: warning
          disabled: false

    staticcheck:
      checks:
        - "all"
        - "-ST1000"
        - "-ST1005"

  exclusions:
    generated: lax
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - funlen
          - gosec
          - noctx
          - prealloc
      - path: _test\.go
        text: unused-parameter

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt

  settings:
    gci:
      sections:
        - standard
        - default
        - localmodule

  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
