version: "3"
services:
  pad:
    image: ghcr.io/dotzero/pad:latest
    container_name: pad
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    ports:
      - "8080:8080"
    environment:
      PAD_HOST: "0.0.0.0"
      PAD_PORT: "8080"
      PAD_SECRET: random_salt_here
    volumes:
      - pad_db:/app/db

volumes:
  pad_db:
