name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
        id: go

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: go build -v ./...
        env:
          GOFLAGS: "-mod=vendor"

      - name: Test
        run: go test -v ./...
        env:
          GOFLAGS: "-mod=vendor"

      - name: Install golangci-lint
        run: |
          curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $GITHUB_WORKSPACE v1.43.0

      - name: Run linters
        run: $GITHUB_WORKSPACE/golangci-lint run
        env:
          GOFLAGS: "-mod=vendor"
